### ISSUE TITLE
Change the default returned search items to 20 (instead of 10)

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#28] opened 2017-04-28 15:16 UTC

**Comment by KarenMajewicz** [comment] 2017-05-03 14:55
When you click the "Back to Search" button on the item view page, it returns to a search results page that only shows 10 items at a time.

**Comment by ewlarson** [comment] 2017-05-03 15:11
Sneaky bug there.  I'll chase it down.

**Comment by ewlarson** [comment] 2017-05-03 16:42
Actually... I can't reproduce this.  Can you tell me step by step how you're seeing the issue?  Thanks!

**Comment by KarenMajewicz** [comment] 2017-05-03 17:49
Ha! It's not doing it anymore.  Must have been a cache thing?

**Comment by ewlarson** [comment] 2017-05-03 18:02
Glad to hear, but there still may be some sequence of steps that exhibits this issue.  I'm going to close this for now, but if you ever see it again let me know!

**Closed by ewlarson** 2017-05-03 18:02 UTC
